#include <Keyboard.h>

#define KEY_SPACE 32
#define KEYS 104

struct KeyboardLayout {
    int key;
    const char* name;
};

KeyboardLayout keys_arr[KEYS] = {
    {KEY_LEFT_CTRL, "Ctrl"},
    {KEY_LEFT_SHIFT, "Shift"},
    {KEY_LEFT_ALT, "Alt"},
    {KEY_LEFT_GUI, "Win"},

    {'0', "0"},
    {'1', "1"},
    {'2', "2"},
    {'3', "3"},
    {'4', "4"},
    {'5', "5"},
    {'6', "6"},
    {'7', "7"},
    {'8', "8"},
    {'9', "9"},
    {'a', "A"},
    {'b', "B"},
    {'c', "C"},
    {'d', "D"},
    {'e', "E"},
    {'f', "F"},
    {'g', "G"},
    {'h', "H"},
    {'i', "I"},
    {'j', "J"},
    {'k', "K"},
    {'l', "L"},
    {'m', "M"},
    {'n', "N"},
    {'o', "O"},
    {'p', "P"},
    {'q', "Q"},
    {'r', "R"},
    {'s', "S"},
    {'t', "T"},
    {'u', "U"},
    {'v', "V"},
    {'w', "W"},
    {'x', "X"},
    {'y', "Y"},
    {'z', "Z"},

    {'.', "."},
    {',', ","},
    {':', ":"},
    {';', ";"},
    {'!', "!"},
    {'?', "?"},
    {'+', "+"},
    {'-', "-"},
    {'_', "_"},
    {'<', "<"},
    {'=', "="},
    {'>', ">"},
    {'(', "("},
    {')', ")"},
    {'[', "["},
    {']', "]"},
    {'{', "{"},
    {'}', "}"},
    {'/', "/"},
    {'|', "|"},
    {'\\', "\\"},
    {'\"', "\""},
    {'\'', "\'"},
    {'#', "#"},
    {'$', "$"},
    {'%', "%"},
    {'&', "&"},
    {'*', "*"},
    {'@', "@"},
    {'^', "^"},
    {'`', "`"},
    {'~', "~"},

    {KEY_ESC, "Esc"},
    {KEY_TAB, "Tab"},
    {KEY_RETURN, "Enter"},
    {KEY_BACKSPACE, "Backspace"},
    {KEY_SPACE, "Space"},

    {KEY_F1, "F1"},
    {KEY_F2, "F2"},
    {KEY_F3, "F3"},
    {KEY_F4, "F4"},
    {KEY_F5, "F5"},
    {KEY_F6, "F6"},
    {KEY_F7, "F7"},
    {KEY_F8, "F8"},
    {KEY_F9, "F9"},
    {KEY_F10, "F10"},
    {KEY_F11, "F11"},
    {KEY_F12, "F12"},

    {KEY_NUM_LOCK, "Num Lock"},
    {KEY_SCROLL_LOCK, "Scroll Lock"},
    {KEY_CAPS_LOCK, "Caps Lock"},
    {KEY_INSERT, "Insert"},
    {KEY_DELETE, "Delete"},
    {KEY_PAUSE, "Pause"},
    {KEY_PAGE_UP, "Page Up"},
    {KEY_PAGE_DOWN, "Page Down"},
    {KEY_END, "End"},
    {KEY_HOME, "Home"},
    {KEY_LEFT_ARROW, "Left Arrow"},
    {KEY_UP_ARROW, "Up Arrow"},
    {KEY_RIGHT_ARROW, "Right Arrow"},
    {KEY_DOWN_ARROW, "Down Arrow"},
    {KEY_PRINT_SCREEN, "Print Screen"}
};